name: Packer Build

on:
  pull_request:
    types: [closed]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install packer
    
    - name: Zip all the webApp files
      run: |
          zip -r webapp.zip ./
          pwd

    - name: Setup Environment File
      run: |
              cat << EOF > .env
              DB_USERNAME: chetan
              DB_PASSWORD: 'Chetan@1234'
              DB_HOST: localhost
              DB_DATABASE: cloud
              DB_DIALECT: postgres
              SERVER_PORT: 8080
              EOF
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAS66UDIGRYPMOA4NB
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Format Packer templates
      run: packer fmt .

    - name: Initiate Packer template
      run: packer init .

    - name: Validate Packer template
      run: packer validate -var-file="dev.pkrvars.hcl" webapp.pkr.hcl 

    - name: Build Packer template
      run: packer build -var-file="dev.pkrvars.hcl" webapp.pkr.hcl 
