name: Packer Build

on:
  pull_request:
    types: [closed]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install packer
    
    - name: Zip all the webApp files
      run: |
          zip -r webapp.zip ./
          pwd

    - name: Setup Environment File
      run: |
              cat << EOF > .env
              DB_USERNAME: ${{ secrets.DB_USERNAME }}
              DB_HOST: ${{ secrets.DB_HOST }}
              DB_DATABASE: ${{ secrets.DB_DATABASE }}
              DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
              DB_DIALECT: ${{ secrets.DB_DIALECT }}
              SERVER_PORT: ${{ secrets.SERVER_PORT }}
              EOF
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Format Packer templates
      run: packer fmt .

    - name: Initiate Packer template
      run: packer init .

    - name: Validate Packer template
      run: packer validate .

    - name: Build Packer template
      run: packer build -var-file="dev.pkrvars.hcl" webapp.pkr.hcl 
