name: integration testing api
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
 
jobs:
    api-test:
        runs-on: ubuntu-latest
        env:
            DB_USER: ${{ secrets.DB_USERNAME }}
            DB_PASS: ${{ secrets.DB_PASSWORD }}
            DB_DB: ${{ secrets.DB_DATABASE }}
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v2
 
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install PostgreSQL and related packages
              run: |
                sudo apt-get update
                sudo apt-get install -y postgresql postgresql-contrib
                sudo systemctl start postgresql
                sudo systemctl enable postgresql
 
            - name: Create PostgreSQL user and database
              run: |
                sudo -u postgres psql -c "CREATE USER chetan WITH PASSWORD 'Chetan@1234';" 2>/dev/null
                sudo -u postgres psql -c "CREATE DATABASE cloud OWNER chetan;" 2>/dev/null
                sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE cloud TO chetan;" 2>/dev/null
                sudo mkdir -p /var/log/webapp 2>/dev/null

            - name: Install Dependencies
              run: npm ci
 
            - name: API testing
              run: npm test
              env:
                  DB_USERNAME: chetan
                  DB_HOST: localhost
                  DB_DATABASE: cloud
                  DB_PASSWORD: 'Chetan@1234'
                  DB_DIALECT: postgres
                  SERVER_PORT: 8080
                  APP_ENV: prod